---
name: Create JIRA ticket for new issues

on:
  issues:
    types: [opened]

jobs:
  jira_task:
    name: Create Jira issue
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Create JIRA ticket
      id: create
      shell: bash
      run: |
        export ISSUE_TITLE="${{ github.event.issue.title }}"
        export ISSUE_BODY="${{ github.event.issue.body }}"
        export ISSUE_URL="${{ github.event.issue.html_url }}"
        export JIRA_API_TOKEN=${{ secrets.JIRA_API_TOKEN }}

        ./.github/scripts/create-jira-ticket.sh

        echo "jira-ticket-id=$(echo $JIRA_TICKET_ID)" >> $GITHUB_OUTPUT
        echo "jira-ticket-link=$(echo $JIRA_TICKET_LINK)" >> $GITHUB_OUTPUT
    - name: Add comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Thanks for opening this issue. The ticket [${{ steps.create.outputs.jira-ticket-id }}](${{ steps.create.outputs.jira-ticket-link }}) was created for internal tracking.
